"""Initial migration.

Revision ID: 3490236c569e
Revises: 
Create Date: 2022-05-24 12:12:33.169693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3490236c569e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=1450), nullable=False),
    sa.Column('website_name', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=36), nullable=False),
    sa.Column('company_description', sa.String(length=1450), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_details')
    # ### end Alembic commands ###
