"""Initial migration.

Revision ID: dfb43faf35d8
Revises: 
Create Date: 2022-05-27 20:50:24.145089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb43faf35d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buld_iot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bulb_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=1450), nullable=False),
    sa.Column('website_name', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=36), nullable=False),
    sa.Column('company_description', sa.String(length=1450), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_details')
    op.drop_table('buld_iot')
    # ### end Alembic commands ###
